spring:
  application:
    name: currency-conversion-service
server:
  port: 8890

forex-service-uri: localhost:8889

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

